language: csharp

install:
  npm i -g typescript
  
script:
  - export EnableNuGetPackageRestore="true"
  - mono src/.nuget/NuGet.exe install Rosalia -ExcludeVersion -Prerelease
  - mono Rosalia/tools/Rosalia.exe /workDirectory=src "CrystalQuartz.Build/CrystalQuartz.Build.csproj" 
